if(NOT PAHO_FOUND)
  find_path(PAHO_INCLUDE_DIRS NAMES MQTTClient.h)
  find_library(PAHO_LIBRARIES NAMES paho-mqtt3c)

if(PAHO_INCLUDE_DIRS AND PAHO_LIBRARIES)
  set(PAHO_FOUND TRUE CACHE INTERNAL "paho found")
  message(STATUS "Found paho: ${PAHO_INCLUDE_DIRS}, ${PAHO_LIBRARIES}")
else(PAHO_INCLUDE_DIRS AND PAHO_LIBRARIES)
  set(PAHO_FOUND FALSE CACHE INTERNAL "paho found")
  message(STATUS "paho not found.")
endif(PAHO_INCLUDE_DIRS AND PAHO_LIBRARIES)

mark_as_advanced(PAHO_LIBRARIES PAHO_INCLUDE_DIRS)

endif(NOT PAHO_FOUND)
